application: seduce-it
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /images
  static_dir: images
- url: /js
  static_dir: js
- url: /check
  script: check.app
- url: /choose
  script: choose.app
- url: /dashboard
  script: dashboard.app
- url: /test
  script: test.app
- url: /test/.*
  script: test2.app
- url: /fblogin
  static_files: fblogin.html
  upload: fblogin.html
- url: /
  script: main.app