application: seduce-it
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /images
  static_dir: images
- url: /js
  static_dir: js
- url: /check
  script: check.app
- url: /events
  static_files: events.html
  upload: events.html
- url: /fblogin
  static_files: fblogin.html
  upload: fblogin.html
- url: /
  script: main.app